name: Node.js Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vala-score

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.5.1'

    - name: Install Dependencies
      run: npm ci
    
    - name: Set git config
      run: |
        git config user.name "GHA Deployer"
        git config user.email "qwex23@users.noreply.github.com"

    - name: Run Deploy
      run: npm run deploy